import heroImage from "../assets/hero-img.png";
import { useLocation } from "wouter";
import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { ArrowRight, BookOpen, Shapes, BrainCircuit, CheckCircle2, Play, Star, Zap, Trophy, Users, ChevronRight, Calculator, Pi, Sigma, Infinity, Mail, Github, Twitter, Youtube, GraduationCap, FlaskConical, Lightbulb, Globe, RotateCcw } from "lucide-react";
import { Button } from "@/components/ui/button";
import { ThreeScene } from "@/components/ThreeScene";
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
const stats = [{
  value: "7",
  label: "Classes Covered",
  icon: BookOpen,
  color: "text-violet-500"
}, {
  value: "50+",
  label: "Chapters",
  icon: Sigma,
  color: "text-blue-500"
}, {
  value: "300+",
  label: "Formulas",
  icon: Pi,
  color: "text-fuchsia-500"
}, {
  value: "200+",
  label: "Quiz Questions",
  icon: Zap,
  color: "text-amber-500"
}];
const steps = [{
  step: "01",
  title: "Pick Your Class",
  desc: "Select your class from 6 to 12 and instantly get the full chapter list for your curriculum.",
  icon: Users,
  color: "bg-violet-500/10 text-violet-500 border-violet-500/20"
}, {
  step: "02",
  title: "Explore & Visualise",
  desc: "Browse beautifully formatted formula cards and interact with live 3D geometric shapes.",
  icon: Shapes,
  color: "bg-blue-500/10 text-blue-500 border-blue-500/20"
}, {
  step: "03",
  title: "Test Yourself",
  desc: "Take chapter-specific quizzes with instant feedback to lock in what you have learnt.",
  icon: Trophy,
  color: "bg-fuchsia-500/10 text-fuchsia-500 border-fuchsia-500/20"
}];
const classes = [{
  cls: "6",
  topics: ["Basic Geometry", "Fractions & Decimals", "Algebra Intro", "Mensuration 2D"],
  color: "from-violet-500 to-purple-700"
}, {
  cls: "7",
  topics: ["Triangles", "Ratio & Proportion", "Linear Equations", "Perimeter & Area"],
  color: "from-blue-500 to-indigo-700"
}, {
  cls: "8",
  topics: ["Squares & Cubes", "Quadrilaterals", "Mensuration 3D", "Algebraic Identities"],
  color: "from-fuchsia-500 to-pink-700"
}, {
  cls: "9",
  topics: ["Number Systems", "Polynomials", "Coordinate Geometry", "Heron's Formula"],
  color: "from-cyan-500 to-blue-700"
}, {
  cls: "10",
  topics: ["Quadratic Equations", "Trigonometry", "Circles", "Surface Areas & Volumes"],
  color: "from-indigo-500 to-violet-700"
}, {
  cls: "11",
  topics: ["Conic Sections", "Sequences & Series", "Permutations", "Limits & Derivatives"],
  color: "from-purple-500 to-fuchsia-700"
}, {
  cls: "12",
  topics: ["Matrices", "Integrals", "Differential Equations", "Vectors & 3D Geometry"],
  color: "from-blue-600 to-cyan-700"
}];
const highlights = ["No login required — open and start instantly", "Covers entire NCERT syllabus from Class 6 to 12", "Drag-to-rotate interactive 3D shape viewer", "Instant quiz feedback with explanations", "Works on any device — desktop, tablet, or phone", "Dark and light mode for comfortable studying"];
const shapeShowcase = [{
  shape: "cube",
  label: "Cube",
  formula: "V = a³   |   SA = 6a²",
  fact: "A cube has 6 identical square faces, 12 edges, and 8 vertices. It is one of the five Platonic solids.",
  color: "from-violet-600 to-purple-800",
  accent: "#7c3aed"
}, {
  shape: "sphere",
  label: "Sphere",
  formula: "V = ⁴⁄₃πr³   |   SA = 4πr²",
  fact: "A sphere is perfectly symmetrical — every point on its surface is equidistant from the centre.",
  color: "from-blue-600 to-indigo-800",
  accent: "#2563eb"
}, {
  shape: "cylinder",
  label: "Cylinder",
  formula: "V = πr²h   |   SA = 2πr(r+h)",
  fact: "A cylinder has two circular bases connected by a curved surface. Its volume equals the base area times height.",
  color: "from-fuchsia-600 to-pink-800",
  accent: "#c026d3"
}, {
  shape: "cone",
  label: "Cone",
  formula: "V = ⅓πr²h   |   SA = πr(r+l)",
  fact: "The slant height l = √(r²+h²). A cone's volume is exactly one-third of a cylinder with the same base and height.",
  color: "from-cyan-600 to-blue-800",
  accent: "#0891b2"
}, {
  shape: "icosahedron",
  label: "Octahedron",
  formula: "V = √2/3 a³   |   F = 8 faces",
  fact: "An octahedron has 8 equilateral triangle faces, 6 vertices, and 12 edges. It is dual to the cube.",
  color: "from-indigo-600 to-violet-800",
  accent: "#4f46e5"
}, {
  shape: "torus",
  label: "Torus",
  formula: "V = 2π²Rr²   |   SA = 4π²Rr",
  fact: "A torus is generated by revolving a circle of radius r around an axis at distance R. It looks like a donut!",
  color: "from-purple-600 to-fuchsia-800",
  accent: "#9333ea"
}];
const footerLinks = {
  "Quick Links": [{
    label: "Home",
    href: "/"
  }, {
    label: "Start Learning",
    href: "/learn"
  }, {
    label: "About MathsLab",
    href: "/"
  }, {
    label: "Class Selector",
    href: "/learn"
  }],
  "Subjects": [{
    label: "Algebra & Numbers",
    href: "/learn"
  }, {
    label: "Geometry",
    href: "/learn"
  }, {
    label: "Trigonometry",
    href: "/learn"
  }, {
    label: "Calculus & Limits",
    href: "/learn"
  }, {
    label: "Statistics",
    href: "/learn"
  }, {
    label: "Probability",
    href: "/learn"
  }],
  "Tools": [{
    label: "Formula Library",
    href: "/learn"
  }, {
    label: "3D Shape Explorer",
    href: "/learn"
  }, {
    label: "Quick Quizzes",
    href: "/learn"
  }, {
    label: "Chapter Guide",
    href: "/learn"
  }, {
    label: "Dark Mode",
    href: "/"
  }],
  "Classes": [{
    label: "Class 6",
    href: "/learn"
  }, {
    label: "Class 7",
    href: "/learn"
  }, {
    label: "Class 8",
    href: "/learn"
  }, {
    label: "Class 9",
    href: "/learn"
  }, {
    label: "Class 10",
    href: "/learn"
  }, {
    label: "Class 11 & 12",
    href: "/learn"
  }]
};
const container = {
  hidden: {},
  show: {
    transition: {
      staggerChildren: 0.1
    }
  }
};
const fadeUp = {
  hidden: {
    opacity: 0,
    y: 24
  },
  show: {
    opacity: 1,
    y: 0,
    transition: {
      duration: 0.5
    }
  }
};
export default function Home() {
  const [, setLocation] = useLocation();
  const [activeShape, setActiveShape] = useState("cube");
  return /*#__PURE__*/_jsxs("div", {
    className: "flex flex-col",
    children: [/*#__PURE__*/_jsx("main", {
      className: "container mx-auto px-4 md:px-8 py-14 lg:py-24 max-w-7xl",
      children: /*#__PURE__*/_jsxs("div", {
        className: "grid lg:grid-cols-2 gap-12 items-center",
        children: [/*#__PURE__*/_jsxs(motion.div, {
          initial: {
            opacity: 0,
            y: 20
          },
          animate: {
            opacity: 1,
            y: 0
          },
          transition: {
            duration: 0.6
          },
          className: "flex flex-col space-y-8 text-center lg:text-left",
          children: [/*#__PURE__*/_jsxs("div", {
            className: "space-y-5",
            children: [/*#__PURE__*/_jsxs("div", {
              className: "inline-flex items-center rounded-full border border-primary/20 bg-primary/10 px-2.5 py-0.5 md:px-3 md:py-1 text-xs md:text-sm font-medium text-primary",
              children: [/*#__PURE__*/_jsx("span", {
                className: "flex h-2 w-2 rounded-full bg-primary mr-2"
              }), "For Class 6\u201312 Students"]
            }), /*#__PURE__*/_jsxs("h1", {
              className: "text-4xl md:text-7xl lg:text-8xl font-bold font-display tracking-tight text-foreground leading-[1.15] md:leading-[1.1]",
              children: ["Learn Maths.", /*#__PURE__*/_jsx("br", {}), /*#__PURE__*/_jsx("span", {
              className: "text-transparent bg-clip-text bg-gradient-to-r from-primary to-fuchsia-500",
                children: "Score Higher."
              })]
            }), /*#__PURE__*/_jsx("p", {
              className: "text-sm md:text-lg text-muted-foreground max-w-[560px] mx-auto lg:mx-0 leading-relaxed",
              children: "Your complete Maths guide for Class 6\u201312. Study chapter-wise, master formulas, test yourself with quizzes \u2014 all in one place, completely free."
            })]
          }), /*#__PURE__*/_jsxs("div", {
            className: "flex flex-col sm:flex-row items-center gap-3 md:gap-4 justify-center lg:justify-start",
            children: [/*#__PURE__*/_jsxs(Button, {
              size: "lg",
              "data-testid": "button-start-learning",
              className: "w-full sm:w-auto text-base h-12 md:h-14 px-8 rounded-full shadow-lg shadow-primary/25 hover:shadow-primary/40 transition-all hover:-translate-y-1",
              onClick: () => setLocation("/learn"),
              children: ["Start Learning Now", /*#__PURE__*/_jsx(ArrowRight, {
                className: "ml-2 h-4 w-4 md:h-5 md:w-5"
              })]
            }), /*#__PURE__*/_jsxs(Button, {
              size: "lg",
              variant: "outline",
              "data-testid": "button-view-syllabus",
              onClick: () => setLocation("/learn"),
              className: "w-full sm:w-auto text-base h-12 md:h-14 px-8 rounded-full",
              children: [/*#__PURE__*/_jsx(Play, {
                className: "mr-2 h-4 w-4 fill-current"
              }), "View Syllabus"]
            })]
          })]
        }), /*#__PURE__*/_jsx(motion.div, {
          initial: {
            opacity: 0,
            scale: 0.9,
            y: 20
          },
          animate: {
            opacity: 1,
            scale: 1,
            y: 0
          },
          transition: {
            duration: 0.8,
            delay: 0.2
          },
          className: "relative h-[300px] md:h-[520px] lg:h-[600px] w-full flex items-center justify-center mt-8 lg:mt-0",
          children: /*#__PURE__*/_jsx("img", {
            src: heroImage,
            alt: "Student learning mathematics with 3D shapes",
            className: "h-full w-full object-contain select-none rounded-3xl",
            draggable: false
          })
        })]
      })
    }), /*#__PURE__*/_jsx("section", {
      className: "border-y border-border bg-secondary/40 py-12",
      children: /*#__PURE__*/_jsx("div", {
        className: "container mx-auto px-4 md:px-8 max-w-5xl",
        children: /*#__PURE__*/_jsx(motion.div, {
          variants: container,
          initial: "hidden",
          whileInView: "show",
          viewport: {
            once: true
          },
          className: "grid grid-cols-2 md:grid-cols-4 gap-6 text-center",
          children: stats.map(({
            value,
            label,
            icon: Icon,
            color
          }) => /*#__PURE__*/_jsxs(motion.div, {
            variants: fadeUp,
            className: "flex flex-col items-center gap-2",
            children: [/*#__PURE__*/_jsx("div", {
              className: `h-10 w-10 rounded-2xl bg-background border border-border flex items-center justify-center ${color}`,
              children: /*#__PURE__*/_jsx(Icon, {
                className: "h-5 w-5"
              })
            }), /*#__PURE__*/_jsx("p", {
              className: "text-3xl font-bold font-display text-foreground",
              children: value
            }), /*#__PURE__*/_jsx("p", {
              className: "text-sm text-muted-foreground",
              children: label
            })]
          }, label))
        })
      })
    }), /*#__PURE__*/_jsx("section", {
      className: "py-20 lg:py-28",
      children: /*#__PURE__*/_jsxs("div", {
        className: "container mx-auto px-4 md:px-8 max-w-7xl",
        children: [/*#__PURE__*/_jsxs(motion.div, {
          initial: {
            opacity: 0,
            y: 16
          },
          whileInView: {
            opacity: 1,
            y: 0
          },
          viewport: {
            once: true
          },
          className: "text-center mb-14",
          children: [/*#__PURE__*/_jsx("p", {
            className: "text-sm font-semibold text-primary uppercase tracking-widest mb-3",
            children: "What you get"
          }), /*#__PURE__*/_jsx("h2", {
            className: "text-3xl md:text-4xl font-bold font-display text-foreground",
            children: "Everything you need to ace Maths"
          })]
        }), /*#__PURE__*/_jsx(motion.div, {
          variants: container,
          initial: "hidden",
          whileInView: "show",
          viewport: {
            once: true
          },
          className: "grid md:grid-cols-3 gap-6",
          children: [{
            icon: BookOpen,
            color: "bg-violet-500/10 text-violet-500",
            title: "Chapter-wise Study",
            desc: "Every chapter of Class 6–12 NCERT Maths — neatly organised with explanations, key concepts, and solved examples."
          }, {
            icon: Calculator,
            color: "bg-fuchsia-500/10 text-fuchsia-500",
            title: "Formula Library",
            desc: "All formulas, theorems, and identities in one place. From basic fractions to differential equations — easy to find, easy to remember."
          }, {
            icon: BrainCircuit,
            color: "bg-blue-500/10 text-blue-500",
            title: "Practice Quizzes",
            desc: "Topic-wise MCQ quizzes to test yourself after every chapter. Instant results with explanations so you learn from mistakes."
          }, {
            icon: Shapes,
            color: "bg-cyan-500/10 text-cyan-500",
            title: "Visual 3D Shapes",
            desc: "Understand mensuration and geometry better with interactive 3D shape models — rotate them, see formulas update live."
          }, {
            icon: Star,
            color: "bg-amber-500/10 text-amber-500",
            title: "Dark & Light Mode",
            desc: "Study comfortably any time of day with a carefully designed dark mode and crisp light mode."
          }, {
            icon: Infinity,
            color: "bg-pink-500/10 text-pink-500",
            title: "Always Free",
            desc: "No login, no paywall, no ads. Just open and start learning. Knowledge should always be accessible."
          }].map(({
            icon: Icon,
            color,
            title,
            desc
          }) => /*#__PURE__*/_jsxs(motion.div, {
            variants: fadeUp,
            className: "group bg-background border border-border rounded-3xl p-8 hover:shadow-lg hover:border-primary/30 transition-all duration-300 hover:-translate-y-1",
            children: [/*#__PURE__*/_jsx("div", {
              className: `h-12 w-12 ${color} rounded-2xl flex items-center justify-center mb-5`,
              children: /*#__PURE__*/_jsx(Icon, {
                className: "h-6 w-6"
              })
            }), /*#__PURE__*/_jsx("h3", {
              className: "text-lg font-bold font-display mb-2 text-foreground",
              children: title
            }), /*#__PURE__*/_jsx("p", {
              className: "text-muted-foreground text-sm leading-relaxed",
              children: desc
            })]
          }, title))
        })]
      })
    }), /*#__PURE__*/_jsx("section", {
      className: "py-20 lg:py-28 bg-secondary/40 border-y border-border",
      children: /*#__PURE__*/_jsxs("div", {
        className: "container mx-auto px-4 md:px-8 max-w-5xl",
        children: [/*#__PURE__*/_jsxs(motion.div, {
          initial: {
            opacity: 0,
            y: 16
          },
          whileInView: {
            opacity: 1,
            y: 0
          },
          viewport: {
            once: true
          },
          className: "text-center mb-14",
          children: [/*#__PURE__*/_jsx("p", {
            className: "text-sm font-semibold text-primary uppercase tracking-widest mb-3",
            children: "Simple to use"
          }), /*#__PURE__*/_jsx("h2", {
            className: "text-3xl md:text-4xl font-bold font-display text-foreground",
            children: "How it works"
          })]
        }), /*#__PURE__*/_jsx(motion.div, {
          variants: container,
          initial: "hidden",
          whileInView: "show",
          viewport: {
            once: true
          },
          className: "grid md:grid-cols-3 gap-8 relative",
          children: steps.map(({
            step,
            title,
            desc,
            icon: Icon,
            color
          }, i) => /*#__PURE__*/_jsxs(motion.div, {
            variants: fadeUp,
            className: "relative flex flex-col items-center text-center",
            children: [/*#__PURE__*/_jsx("div", {
              className: `h-16 w-16 rounded-2xl border ${color} flex items-center justify-center mb-5`,
              children: /*#__PURE__*/_jsx(Icon, {
                className: "h-7 w-7"
              })
            }), /*#__PURE__*/_jsx("span", {
              className: "absolute -top-3 -right-3 text-xs font-bold text-muted-foreground/30 font-display text-5xl select-none",
              children: step
            }), /*#__PURE__*/_jsx("h3", {
              className: "text-lg font-bold font-display mb-2 text-foreground",
              children: title
            }), /*#__PURE__*/_jsx("p", {
              className: "text-muted-foreground text-sm leading-relaxed",
              children: desc
            }), i < steps.length - 1 && /*#__PURE__*/_jsx(ChevronRight, {
              className: "hidden md:block absolute top-7 -right-5 h-6 w-6 text-muted-foreground/30"
            })]
          }, step))
        })]
      })
    }), /*#__PURE__*/_jsx("section", {
      className: "py-20 lg:py-28",
      children: /*#__PURE__*/_jsxs("div", {
        className: "container mx-auto px-4 md:px-8 max-w-7xl",
        children: [/*#__PURE__*/_jsxs(motion.div, {
          initial: {
            opacity: 0,
            y: 16
          },
          whileInView: {
            opacity: 1,
            y: 0
          },
          viewport: {
            once: true
          },
          className: "text-center mb-14",
          children: [/*#__PURE__*/_jsx("p", {
            className: "text-sm font-semibold text-primary uppercase tracking-widest mb-3",
            children: "Browse by class"
          }), /*#__PURE__*/_jsx("h2", {
            className: "text-3xl md:text-4xl font-bold font-display text-foreground",
            children: "Find your class"
          }), /*#__PURE__*/_jsx("p", {
            className: "text-muted-foreground mt-3 max-w-lg mx-auto",
            children: "Every class has its own complete chapter library, formula set, and quiz bank."
          })]
        }), /*#__PURE__*/_jsxs(motion.div, {
          variants: container,
          initial: "hidden",
          whileInView: "show",
          viewport: {
            once: true
          },
          className: "grid grid-cols-2 lg:grid-cols-4 gap-3 md:gap-5",
          children: [classes.map(({
            cls,
            topics,
            color
          }) => /*#__PURE__*/_jsxs(motion.button, {
            variants: fadeUp,
            "data-testid": `button-class-${cls}`,
            onClick: () => setLocation("/learn"),
            className: "group relative bg-background border border-border rounded-3xl overflow-hidden text-left hover:shadow-xl hover:-translate-y-1 transition-all duration-300 hover:border-primary/30",
            children: [/*#__PURE__*/_jsx("div", {
              className: `h-2 w-full bg-gradient-to-r ${color}`
            }), /*#__PURE__*/_jsxs("div", {
              className: "p-4 md:p-6",
              children: [/*#__PURE__*/_jsxs("div", {
                className: "flex items-center justify-between mb-4",
                children: [/*#__PURE__*/_jsx("span", {
                  className: `text-3xl md:text-4xl font-extrabold font-display text-transparent bg-clip-text bg-gradient-to-br ${color}`,
                  children: cls
                }), /*#__PURE__*/_jsx("span", {
                  className: "text-xs font-semibold text-muted-foreground uppercase tracking-wider",
                  children: "Class"
                })]
              }), /*#__PURE__*/_jsx("ul", {
                className: "space-y-1.5",
                children: topics.map(t => /*#__PURE__*/_jsxs("li", {
                  className: "flex items-start gap-2 text-[13px] md:text-sm text-muted-foreground leading-snug",
                  children: [/*#__PURE__*/_jsx("span", {
                    className: "h-1.5 w-1.5 rounded-full bg-primary/50 flex-shrink-0 mt-1.5"
                  }), t]
                }, t))
              }), /*#__PURE__*/_jsxs("div", {
                className: "mt-4 md:mt-5 flex items-center gap-1 text-[11px] md:text-xs font-semibold text-primary group-hover:gap-2 transition-all",
                children: ["Open ", /*#__PURE__*/_jsx(ChevronRight, {
                  className: "h-3 w-3"
                })]
              })]
            })]
          }, cls)), /*#__PURE__*/_jsxs(motion.div, {
            variants: fadeUp,
            className: "relative bg-gradient-to-br from-primary/10 to-fuchsia-500/10 border border-primary/20 rounded-3xl overflow-hidden flex flex-col items-center justify-center p-4 md:p-6 min-h-[180px] md:min-h-[220px]",
            children: [/*#__PURE__*/_jsx("div", {
              className: "h-20 w-20 md:h-28 md:w-28 mb-3",
              children: /*#__PURE__*/_jsx(ThreeScene, {
                shapeType: "cube"
              })
            }), /*#__PURE__*/_jsx("p", {
              className: "text-xs md:text-sm font-semibold text-foreground text-center",
              children: "3D Shape Explorer"
            }), /*#__PURE__*/_jsx("p", {
              className: "text-xs text-muted-foreground text-center mt-1",
              children: "Drag to rotate"
            })]
          })]
        })]
      })
    }), /*#__PURE__*/_jsx("section", {
      className: "py-20 lg:py-28 border-y border-border bg-secondary/40",
      children: /*#__PURE__*/_jsxs("div", {
        className: "container mx-auto px-4 md:px-8 max-w-7xl",
        children: [/*#__PURE__*/_jsxs(motion.div, {
          initial: {
            opacity: 0,
            y: 16
          },
          whileInView: {
            opacity: 1,
            y: 0
          },
          viewport: {
            once: true
          },
          className: "text-center mb-14",
          children: [/*#__PURE__*/_jsx("p", {
            className: "text-sm font-semibold text-primary uppercase tracking-widest mb-3",
            children: "Visual Learning Tool"
          }), /*#__PURE__*/_jsx("h2", {
            className: "text-3xl md:text-4xl font-bold font-display text-foreground",
            children: "See it. Rotate it. Get it."
          }), /*#__PURE__*/_jsx("p", {
            className: "text-muted-foreground mt-3 max-w-xl mx-auto",
            children: "Geometry and mensuration become easy when you can see them. Drag any shape below to rotate it \u2014 the formula and a quick fact update live as you switch."
          })]
        }), /*#__PURE__*/_jsx(motion.div, {
          initial: {
            opacity: 0,
            y: 24
          },
          whileInView: {
            opacity: 1,
            y: 0
          },
          viewport: {
            once: true
          },
          transition: {
            duration: 0.6
          },
          className: "rounded-[2rem] border border-border bg-background overflow-hidden shadow-2xl",
          children: /*#__PURE__*/_jsxs("div", {
            className: "grid lg:grid-cols-[280px_1fr] min-h-[480px]",
            children: [/*#__PURE__*/_jsxs("div", {
              className: "border-r border-border p-5 space-y-2 bg-secondary/30",
              children: [/*#__PURE__*/_jsx("p", {
                className: "text-xs font-bold text-muted-foreground uppercase tracking-widest mb-4 px-2",
                children: "Select Shape"
              }), shapeShowcase.map(s => /*#__PURE__*/_jsxs("button", {
                "data-testid": `shape-btn-${s.shape}`,
                onClick: () => setActiveShape(s.shape),
                className: `w-full flex items-center gap-3 px-4 py-3 rounded-2xl text-left transition-all duration-200 ${activeShape === s.shape ? "bg-primary text-primary-foreground shadow-lg shadow-primary/30" : "hover:bg-secondary text-foreground"}`,
                children: [/*#__PURE__*/_jsx("div", {
                  className: `h-8 w-8 rounded-xl bg-gradient-to-br ${s.color} flex-shrink-0`
                }), /*#__PURE__*/_jsxs("div", {
                  children: [/*#__PURE__*/_jsx("p", {
                    className: "text-sm font-semibold",
                    children: s.label
                  }), /*#__PURE__*/_jsx("p", {
                    className: `text-xs ${activeShape === s.shape ? "text-primary-foreground/70" : "text-muted-foreground"}`,
                    children: s.formula.split("|")[0].trim()
                  })]
                }), activeShape === s.shape && /*#__PURE__*/_jsx(ChevronRight, {
                  className: "ml-auto h-4 w-4 flex-shrink-0"
                })]
              }, s.shape))]
            }), /*#__PURE__*/_jsxs("div", {
              className: "flex flex-col lg:flex-row",
              children: [/*#__PURE__*/_jsxs("div", {
                className: "relative flex-1 flex items-center justify-center min-h-[300px] lg:min-h-0",
                style: {
                  background: "radial-gradient(circle at 50% 50%, rgba(109,40,217,0.08) 0%, transparent 70%)"
                },
                children: [/*#__PURE__*/_jsx("div", {
                  className: "absolute inset-0 pointer-events-none opacity-20",
                  style: {
                    backgroundImage: "radial-gradient(circle, rgba(139,92,246,0.15) 1px, transparent 1px)",
                    backgroundSize: "24px 24px"
                  }
                }), /*#__PURE__*/_jsx(AnimatePresence, {
                  mode: "wait",
                  children: /*#__PURE__*/_jsx(motion.div, {
                    initial: {
                      opacity: 0,
                      scale: 0.8
                    },
                    animate: {
                      opacity: 1,
                      scale: 1
                    },
                    exit: {
                      opacity: 0,
                      scale: 0.8
                    },
                    transition: {
                      duration: 0.35
                    },
                    className: "h-64 w-64 lg:h-80 lg:w-80",
                    children: /*#__PURE__*/_jsx(ThreeScene, {
                      shapeType: activeShape
                    })
                  }, activeShape)
                }), /*#__PURE__*/_jsxs("div", {
                  className: "absolute bottom-4 left-1/2 -translate-x-1/2 flex items-center gap-2 bg-background/80 backdrop-blur-md px-3 py-1.5 rounded-full border border-border text-xs text-muted-foreground",
                  children: [/*#__PURE__*/_jsx(RotateCcw, {
                    className: "h-3 w-3"
                  }), "Drag to rotate"]
                })]
              }), /*#__PURE__*/_jsx("div", {
                className: "lg:w-72 p-8 border-t lg:border-t-0 lg:border-l border-border flex flex-col justify-center",
                children: /*#__PURE__*/_jsx(AnimatePresence, {
                  mode: "wait",
                  children: shapeShowcase.filter(s => s.shape === activeShape).map(s => /*#__PURE__*/_jsxs(motion.div, {
                    initial: {
                      opacity: 0,
                      x: 16
                    },
                    animate: {
                      opacity: 1,
                      x: 0
                    },
                    exit: {
                      opacity: 0,
                      x: -16
                    },
                    transition: {
                      duration: 0.3
                    },
                    children: [/*#__PURE__*/_jsxs("div", {
                      className: `inline-flex items-center gap-2 px-3 py-1 rounded-full bg-gradient-to-r ${s.color} text-white text-xs font-semibold mb-4`,
                      children: [/*#__PURE__*/_jsx(Shapes, {
                        className: "h-3 w-3"
                      }), s.label]
                    }), /*#__PURE__*/_jsx("h3", {
                      className: "text-lg font-bold font-display text-foreground mb-2",
                      children: "Formula"
                    }), /*#__PURE__*/_jsx("div", {
                      className: "bg-secondary/60 rounded-xl p-4 mb-5 border border-border",
                      children: /*#__PURE__*/_jsx("p", {
                        className: "font-mono text-sm text-foreground leading-relaxed",
                        children: s.formula
                      })
                    }), /*#__PURE__*/_jsxs("h3", {
                      className: "text-sm font-bold font-display text-foreground mb-2 flex items-center gap-2",
                      children: [/*#__PURE__*/_jsx(Lightbulb, {
                        className: "h-4 w-4 text-amber-500"
                      }), "Did you know?"]
                    }), /*#__PURE__*/_jsx("p", {
                      className: "text-sm text-muted-foreground leading-relaxed",
                      children: s.fact
                    }), /*#__PURE__*/_jsxs(Button, {
                      size: "sm",
                      className: "mt-6 rounded-full",
                      onClick: () => setLocation("/learn"),
                      children: ["Explore in Lab", /*#__PURE__*/_jsx(ArrowRight, {
                        className: "ml-1.5 h-3.5 w-3.5"
                      })]
                    })]
                  }, s.shape))
                })
              })]
            })]
          })
        })]
      })
    }), /*#__PURE__*/_jsx("section", {
      className: "py-20 lg:py-28",
      children: /*#__PURE__*/_jsx("div", {
        className: "container mx-auto px-4 md:px-8 max-w-6xl",
        children: /*#__PURE__*/_jsxs("div", {
          className: "grid lg:grid-cols-2 gap-14 items-center",
          children: [/*#__PURE__*/_jsxs(motion.div, {
            initial: {
              opacity: 0,
              x: -24
            },
            whileInView: {
              opacity: 1,
              x: 0
            },
            viewport: {
              once: true
            },
            transition: {
              duration: 0.6
            },
            children: [/*#__PURE__*/_jsx("p", {
              className: "text-sm font-semibold text-primary uppercase tracking-widest mb-3",
              children: "Built for India's classrooms"
            }), /*#__PURE__*/_jsxs("h2", {
              className: "text-3xl md:text-4xl font-bold font-display text-foreground mb-5",
              children: ["Designed for students,", /*#__PURE__*/_jsx("br", {}), "trusted by teachers"]
            }), /*#__PURE__*/_jsx("p", {
              className: "text-muted-foreground leading-relaxed mb-8",
              children: "Mathrix bridges the gap between abstract equations and real understanding \u2014 built specifically for school Maths Labs across India, covering the complete NCERT curriculum."
            }), /*#__PURE__*/_jsx("ul", {
              className: "space-y-3",
              children: highlights.map(h => /*#__PURE__*/_jsxs("li", {
                className: "flex items-start gap-3 text-sm text-foreground",
                children: [/*#__PURE__*/_jsx(CheckCircle2, {
                  className: "h-5 w-5 text-primary flex-shrink-0 mt-0.5"
                }), h]
              }, h))
            })]
          }), /*#__PURE__*/_jsx(motion.div, {
            initial: {
              opacity: 0,
              x: 24
            },
            whileInView: {
              opacity: 1,
              x: 0
            },
            viewport: {
              once: true
            },
            transition: {
              duration: 0.6,
              delay: 0.15
            },
            className: "grid grid-cols-2 gap-5",
            children: [{
              icon: GraduationCap,
              color: "text-violet-500 bg-violet-500/10",
              title: "NCERT Aligned",
              desc: "Every chapter follows the official Class 6–12 NCERT curriculum structure."
            }, {
              icon: FlaskConical,
              color: "text-blue-500 bg-blue-500/10",
              title: "Maths Lab Ready",
              desc: "Designed specifically for school Maths Labs with visual, hands-on learning."
            }, {
              icon: Globe,
              color: "text-fuchsia-500 bg-fuchsia-500/10",
              title: "Any Device",
              desc: "Works on desktop, tablet, and phone — no app installation needed."
            }, {
              icon: Zap,
              color: "text-amber-500 bg-amber-500/10",
              title: "Instant Access",
              desc: "No login, no sign-up. Open the site and start learning in seconds."
            }].map(({
              icon: Icon,
              color,
              title,
              desc
            }) => /*#__PURE__*/_jsxs("div", {
              className: "bg-background border border-border rounded-2xl p-6 hover:border-primary/30 hover:shadow-md transition-all duration-300",
              children: [/*#__PURE__*/_jsx("div", {
                className: `h-10 w-10 ${color} rounded-xl flex items-center justify-center mb-4`,
                children: /*#__PURE__*/_jsx(Icon, {
                  className: "h-5 w-5"
                })
              }), /*#__PURE__*/_jsx("h4", {
                className: "font-bold text-sm text-foreground mb-1",
                children: title
              }), /*#__PURE__*/_jsx("p", {
                className: "text-xs text-muted-foreground leading-relaxed",
                children: desc
              })]
            }, title))
          })]
        })
      })
    }), /*#__PURE__*/_jsx("section", {
      className: "py-16 bg-secondary/40 border-y border-border",
      children: /*#__PURE__*/_jsx("div", {
        className: "container mx-auto px-4 md:px-8 max-w-3xl text-center",
        children: /*#__PURE__*/_jsxs(motion.div, {
          initial: {
            opacity: 0,
            y: 16
          },
          whileInView: {
            opacity: 1,
            y: 0
          },
          viewport: {
            once: true
          },
          children: [/*#__PURE__*/_jsx("div", {
            className: "text-7xl font-display text-primary/20 leading-none mb-2 select-none",
            children: "\""
          }), /*#__PURE__*/_jsx("blockquote", {
            className: "text-2xl md:text-3xl font-bold font-display text-foreground leading-snug",
            children: "Mathematics is not about numbers, equations, or algorithms \u2014 it is about understanding."
          }), /*#__PURE__*/_jsx("p", {
            className: "mt-5 text-muted-foreground font-medium",
            children: "William Paul Thurston \u2014 Fields Medal Laureate"
          })]
        })
      })
    }), /*#__PURE__*/_jsx("section", {
      className: "py-20 lg:py-28",
      children: /*#__PURE__*/_jsx("div", {
        className: "container mx-auto px-4 md:px-8 max-w-5xl",
        children: /*#__PURE__*/_jsxs(motion.div, {
          initial: {
            opacity: 0,
            y: 24
          },
          whileInView: {
            opacity: 1,
            y: 0
          },
          viewport: {
            once: true
          },
          className: "relative rounded-[2.5rem] overflow-hidden border border-primary/20 bg-gradient-to-br from-primary/10 via-fuchsia-500/5 to-blue-500/10 px-8 py-16 text-center",
          children: [/*#__PURE__*/_jsx("div", {
            className: "absolute inset-0 pointer-events-none",
            style: {
              backgroundImage: "radial-gradient(circle at 50% 50%, hsl(var(--primary)/0.12) 0%, transparent 70%)"
            }
          }), /*#__PURE__*/_jsxs("h2", {
            className: "text-3xl md:text-5xl font-bold font-display text-foreground mb-4 relative z-10",
            children: ["Ready to", " ", /*#__PURE__*/_jsx("span", {
              className: "text-transparent bg-clip-text bg-gradient-to-r from-primary to-fuchsia-500",
              children: "excel in Maths?"
            })]
          }), /*#__PURE__*/_jsx("p", {
            className: "text-muted-foreground text-lg max-w-xl mx-auto mb-8 relative z-10",
            children: "Join thousands of students who study smarter \u2014 not harder. Pick your class and start today."
          }), /*#__PURE__*/_jsxs(Button, {
            size: "lg",
            "data-testid": "button-cta-start",
            className: "h-14 px-10 text-base rounded-full shadow-xl shadow-primary/30 hover:shadow-primary/50 hover:-translate-y-1 transition-all relative z-10",
            onClick: () => setLocation("/learn"),
            children: ["Start Learning Now", /*#__PURE__*/_jsx(ArrowRight, {
              className: "ml-2 h-5 w-5"
            })]
          })]
        })
      })
    }), /*#__PURE__*/_jsxs("footer", {
      className: "border-t border-border bg-secondary/30",
      children: [/*#__PURE__*/_jsx("div", {
        className: "container mx-auto px-4 md:px-8 max-w-7xl py-16",
        children: /*#__PURE__*/_jsxs("div", {
          className: "grid md:grid-cols-2 lg:grid-cols-6 gap-10",
          children: [/*#__PURE__*/_jsxs("div", {
            className: "lg:col-span-2",
            children: [/*#__PURE__*/_jsxs("div", {
              className: "flex items-center gap-2 font-bold font-display text-foreground mb-4",
              children: [/*#__PURE__*/_jsx("div", {
                className: "h-9 w-9 rounded-xl bg-gradient-to-br from-primary to-fuchsia-600 flex items-center justify-center shadow-lg shadow-primary/30",
                children: /*#__PURE__*/_jsx(Pi, {
                  className: "h-5 w-5 text-white"
                })
              }), /*#__PURE__*/_jsx("span", {
                className: "text-xl",
                children: "Mathrix"
              })]
            }), /*#__PURE__*/_jsx("p", {
              className: "text-sm text-muted-foreground leading-relaxed mb-6 max-w-xs",
              children: "An interactive mathematics learning platform built for school Maths Labs across India. Visual, spatial, and always free."
            }), /*#__PURE__*/_jsx("div", {
              className: "flex flex-wrap gap-2 mb-6",
              children: ["NCERT Aligned", "Class 6–12", "Free Forever"].map(tag => /*#__PURE__*/_jsx("span", {
                className: "text-xs px-3 py-1 rounded-full border border-primary/20 bg-primary/5 text-primary font-medium",
                children: tag
              }, tag))
            }), /*#__PURE__*/_jsx("div", {
              className: "flex items-center gap-3",
              children: [{
                icon: Twitter,
                label: "Twitter"
              }, {
                icon: Github,
                label: "GitHub"
              }, {
                icon: Youtube,
                label: "YouTube"
              }, {
                icon: Mail,
                label: "Email"
              }].map(({
                icon: Icon,
                label
              }) => /*#__PURE__*/_jsx("button", {
                "data-testid": `footer-social-${label.toLowerCase()}`,
                className: "h-9 w-9 rounded-xl border border-border bg-background flex items-center justify-center text-muted-foreground hover:text-primary hover:border-primary/40 transition-colors",
                title: label,
                children: /*#__PURE__*/_jsx(Icon, {
                  className: "h-4 w-4"
                })
              }, label))
            })]
          }), Object.entries(footerLinks).map(([heading, links]) => /*#__PURE__*/_jsxs("div", {
            children: [/*#__PURE__*/_jsx("h4", {
              className: "text-sm font-bold text-foreground mb-4",
              children: heading
            }), /*#__PURE__*/_jsx("ul", {
              className: "space-y-2.5",
              children: links.map(({
                label,
                href
              }) => /*#__PURE__*/_jsx("li", {
                children: /*#__PURE__*/_jsx("button", {
                  onClick: () => setLocation(href),
                  className: "text-sm text-muted-foreground hover:text-primary transition-colors text-left",
                  children: label
                })
              }, label))
            })]
          }, heading))]
        })
      }), /*#__PURE__*/_jsx("div", {
        className: "border-t border-border",
        children: /*#__PURE__*/_jsx("div", {
          className: "container mx-auto px-4 md:px-8 max-w-7xl py-6",
          children: /*#__PURE__*/_jsx("div", {
            className: "flex flex-wrap justify-center gap-8 text-center",
            children: [{
              value: "7",
              label: "Classes"
            }, {
              value: "50+",
              label: "Chapters"
            }, {
              value: "300+",
              label: "Formulas"
            }, {
              value: "6",
              label: "3D Shapes"
            }, {
              value: "200+",
              label: "Quiz Questions"
            }].map(({
              value,
              label
            }) => /*#__PURE__*/_jsxs("div", {
              className: "flex items-center gap-2",
              children: [/*#__PURE__*/_jsx("span", {
                className: "text-lg font-bold font-display text-primary",
                children: value
              }), /*#__PURE__*/_jsx("span", {
                className: "text-sm text-muted-foreground",
                children: label
              })]
            }, label))
          })
        })
      }), /*#__PURE__*/_jsx("div", {
        className: "border-t border-border",
        children: /*#__PURE__*/_jsxs("div", {
          className: "container mx-auto px-4 md:px-8 max-w-7xl py-5 flex flex-col sm:flex-row items-center justify-between gap-3 text-xs text-muted-foreground",
          children: [/*#__PURE__*/_jsx("p", {
            children: "\xA9 2026 Mathrix. Free Maths learning for every student."
          }), /*#__PURE__*/_jsx("p", {
            className: "text-center",
            children: "Class 6\u201312 \xB7 NCERT Aligned \xB7 Always Free"
          }), /*#__PURE__*/_jsxs("div", {
            className: "flex items-center gap-4",
            children: [/*#__PURE__*/_jsx("button", {
              className: "hover:text-primary transition-colors",
              children: "Privacy"
            }), /*#__PURE__*/_jsx("button", {
              className: "hover:text-primary transition-colors",
              children: "Terms"
            }), /*#__PURE__*/_jsx("button", {
              className: "hover:text-primary transition-colors",
              children: "Contact"
            })]
          })]
        })
      })]
    })]
  });
}
